import create from 'zustand';

const useUserStore = create((set) => ({
        select: '',
        status: true,
        func: '',
        finish: '',
        stop: '',
        check:'',
        reff:'',
        inp1:'',
        content1:'',
        sentence:[],
        incorrect:'',
        clic:0,
        eror:0,
        dark:true,
        time:0,
        sec:0,
        page6:'',
        stat:'',
        time1:'',
        time2:'',
        lang:false,
        repeat:'',
        paus:true,
        updateUser: (newSelect, newcheck) => set({ select: newSelect, check: newcheck}),
        updateUser2: (newFunc, newFinish, newStop) => set({ func: newFunc, finish: newFinish, stop: newStop }),
        updateUser3: (newreff) => set({ reff: newreff}),
        updateUser4: (newinp1) => set({ inp1: newinp1}),
        updateUser5: (newcontent1, newsentence) => set({ content1: newcontent1, sentence:newsentence }),
        updateUser6: (newincorrect) => set({ incorrect: newincorrect }),
        updateUser7: (newclic, neweror, newlang) => set({ clic: newclic, eror: neweror, lang:newlang }),
        updateUser8: (newdark) => set({ dark: newdark }),
        updateUser9: (newtime, newsec) => set({ time: newtime, sec: newsec }),
        updateUser10: (newpage6) => set({ page6: newpage6 }),
        updateUser11: (newStat) => set({ stat:  newStat }),
        updateUser12: (newTime1, newTime2) => set({ time1: newTime1, time2: newTime2 }),
        updateUser13: (newpaus) => set({ paus: newpaus}),

}));
export default useUserStore;
